import { flushPromises, mount } from "@vue/test-utils";
import { beforeEach, expect, it, vi } from "vitest";
import { open } from "@tauri-apps/plugin-dialog";
import ApplicationBackup from "./ApplicationBackup.vue";
import AttachmentStoragePanel from "./AttachmentStoragePanel.vue";
import { previewBackup, importBackup } from "../api/backups";
import { getAttachmentStorage, previewAttachmentCleanup, applyAttachmentCleanup } from "../api/attachmentStorage";
const confirm = vi.hoisted(() => vi.fn());
vi.mock("../stores/notifications", () => ({ useNotifications: () => ({ confirm }) }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: vi.fn() }));
vi.mock("../api/backups", () => ({ previewBackup: vi.fn(), importBackup: vi.fn(), exportBackup: vi.fn() }));
vi.mock("../api/attachmentStorage", () => ({ getAttachmentStorage: vi.fn(), previewAttachmentCleanup: vi.fn(), applyAttachmentCleanup: vi.fn() }));
beforeEach(() => { vi.clearAllMocks(); confirm.mockResolvedValue(true); });
it("预览冲突与目录映射，未选完整目录时不能恢复数据", async () => {
  vi.mocked(open).mockResolvedValue("F:/fixture/backup.json");
  vi.mocked(previewBackup).mockResolvedValue({ sha256: "a".repeat(64), kind: "application", home_layout: "compact", counts: { drafts: 1 }, warnings: [], providers: [{ id: "one", name: "模型服务", base_url: "https://fixture.test", conflict: true }], projects: [{ id: 1, name: "项目", root_path: "F:/old" }], workspaces: [{ id: 2, project_id: 1, root_path: "F:/old", kind: "root" }] });
  const wrapper = mount(ApplicationBackup);
  await wrapper.findAll("button").find(button => button.text() === "选择备份并预览")!.trigger("click"); await flushPromises();
  expect(wrapper.text()).toContain("同名冲突：保留本机配置");
  const restore = wrapper.findAll("button").find(button => button.text() === "确认恢复历史、草稿和附件")!;
  expect(restore.attributes("disabled")).toBeDefined();
  vi.mocked(open).mockResolvedValue("F:/new-project");
  await wrapper.findAll("button").find(button => button.text() === "选择项目目录")!.trigger("click"); await flushPromises();
  expect(restore.attributes("disabled")).toBeUndefined();
  expect(importBackup).not.toHaveBeenCalled();
  vi.mocked(importBackup).mockResolvedValue({}); await restore.trigger("click"); await flushPromises();
  expect(importBackup).toHaveBeenCalledWith("F:/fixture/backup.json", "a".repeat(64), "data", { "1": "F:/new-project" }, { "2": "F:/new-project" });
  wrapper.unmount();
});
it("清理先显示引用和空间影响，取消后不执行删除", async () => {
  const item = { id: "a".repeat(32), name: "材料.txt", size_bytes: 20, sha256: "b".repeat(64), project_id: 1, workspace_id: 2, language: "txt", project_name: "项目", read_status: "可预览", drafts: [{ id: "c".repeat(32), title: "当前草稿", session_id: null, scope_key: "scope", revision: 1 }], sessions: [] };
  vi.mocked(getAttachmentStorage).mockResolvedValue({ total: 1, size_bytes: 20, offset: 0, items: [item], cache_bytes: 0, cache_policy: "按需解码", retention: "保留原件" });
  vi.mocked(previewAttachmentCleanup).mockResolvedValue({ version: "version", attachment_id: item.id, draft_id: item.drafts[0].id, name: item.name, draft: item.drafts[0], remaining_drafts: 0, sessions: [], reclaim_bytes: 20 });
  confirm.mockResolvedValue(false);
  const wrapper = mount(AttachmentStoragePanel, { global: { stubs: { TaskAttachmentList: true } } });
  await flushPromises();
  await wrapper.findAll("button").find(button => button.text() === "预览移除影响")!.trigger("click"); await flushPromises();
  expect(confirm.mock.calls[0][0].impact).toContain("预计释放 20 B");
  expect(applyAttachmentCleanup).not.toHaveBeenCalled();
  wrapper.unmount();
});
