"""Agent 协议 codegen：从单一 schema 源生成 Python/TypeScript 契约与 JSON Schema 束。

上位计划 §8.5 / S1-T8：schema 是 Python/TS/fixtures 的唯一事实源；
本脚本生成物禁止手改，CI/测试以 --check 校验零 diff。

Usage:
    uv run python scripts/protocol_codegen.py           # 生成（覆盖写入）
    uv run python scripts/protocol_codegen.py --check   # 只校验，存在差异退出码 1
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = (
    PROJECT_ROOT
    / "src"
    / "personal_assistant"
    / "agent_v2"
    / "protocol"
    / "schema"
    / "agent_protocol.schema.json"
)
PY_OUT = (
    PROJECT_ROOT
    / "src"
    / "personal_assistant"
    / "agent_v2"
    / "protocol"
    / "generated"
    / "models.py"
)
PY_INIT_OUT = (
    PROJECT_ROOT
    / "src"
    / "personal_assistant"
    / "agent_v2"
    / "protocol"
    / "generated"
    / "__init__.py"
)
TS_OUT = (
    PROJECT_ROOT
    / "apps"
    / "desktop"
    / "src"
    / "features"
    / "agent-v2"
    / "protocol"
    / "generated"
    / "agentProtocol.ts"
)
BUNDLE_OUT = (
    PROJECT_ROOT
    / "src"
    / "personal_assistant"
    / "agent_v2"
    / "protocol"
    / "generated"
    / "schema_bundle.json"
)

DO_NOT_EDIT_PY = (
    '"""GENERATED by scripts/protocol_codegen.py — DO NOT EDIT BY HAND.\n\n'
    "Source of truth: agent_v2/protocol/schema/agent_protocol.schema.json\n"
    'Regenerate: uv run python scripts/protocol_codegen.py\n"""'
)
DO_NOT_EDIT_TS = (
    "// GENERATED by scripts/protocol_codegen.py — DO NOT EDIT BY HAND.\n"
    "// Source of truth: agent_v2/protocol/schema/agent_protocol.schema.json\n"
    "// Regenerate: uv run python scripts/protocol_codegen.py\n"
)


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def render_python(schema: dict) -> str:
    proto = schema["protocol"]
    domain = schema["domain"]
    lines: list[str] = [
        DO_NOT_EDIT_PY,
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        f'PROTOCOL_NAME = "{proto["name"]}"',
        f'PROTOCOL_VERSION_MAJOR = {proto["version_major"]}',
        f'PROTOCOL_VERSION_DRAFT = "{proto["version_draft"]}"',
        f'JSONRPC_VERSION = "{proto["jsonrpc"]}"',
        f'MAX_LINE_BYTES = {proto["wire"]["max_line_bytes"]}',
        "",
        "# --- 方法注册表（上位计划 §8.2） ---",
        "METHOD_REGISTRY: dict[str, dict[str, bool | str]] = {",
    ]
    for method in schema["methods"]:
        lines.append(
            f'    "{method["name"]}": {{"kind": "{method["kind"]}", '
            f'"write": {method["write"]}, '
            f'"idempotency_key": {method["idempotency_key"]}}},'
        )
    lines += [
        "}",
        "METHOD_NAMES = frozenset(METHOD_REGISTRY)",
        "WRITE_METHODS = frozenset(m for m, spec in METHOD_REGISTRY.items() if spec['write'])",
        "IDEMPOTENT_KEY_METHODS = frozenset(",
        "    m for m, spec in METHOD_REGISTRY.items() if spec['idempotency_key']",
        ")",
        "",
        "# --- 通知（上位计划 §8.3） ---",
        "NOTIFICATION_TYPES = frozenset({",
    ]
    lines += [f'    "{name}",' for name in schema["notifications"]]
    lines += [
        "})",
        "",
        "# --- 领域枚举（ADR-001） ---",
        "THREAD_STATUSES = frozenset({%s})"
        % ", ".join(f'"{s}"' for s in domain["thread_statuses"]),
        "TURN_STATUSES = frozenset({%s})"
        % ", ".join(f'"{s}"' for s in domain["turn_statuses"]),
        "ITEM_KINDS = frozenset({%s})" % ", ".join(f'"{k}"' for k in domain["item_kinds"]),
        "ITEM_LIFECYCLE = frozenset({%s})"
        % ", ".join(f'"{s}"' for s in domain["item_lifecycle"]),
        "CONTEXT_FRAGMENT_KINDS = frozenset({%s})"
        % ", ".join(f'"{k}"' for k in domain["context_fragment_kinds"]),
        "ITEM_REQUIRED_FIELDS = frozenset({%s})"
        % ", ".join(f'"{f}"' for f in domain["item_required_fields"]),
        "",
        "",
        "class _ProtocolModel(BaseModel):",
        '    model_config = ConfigDict(extra="forbid", frozen=True)',
        "",
        "",
        "class JsonRpcError(_ProtocolModel):",
        '    """固定五字段错误信封（上位计划 §8.4-6 / ADR-002）。"""',
        "",
        "    code: int",
        "    message: str",
        "    retryable: bool",
        '    details: str = ""',
        '    trace_id: str = ""',
        "",
        "",
        "class JsonRpcRequest(_ProtocolModel):",
        f'    jsonrpc: Literal["{proto["jsonrpc"]}"]',
        "    id: str | int",
        "    method: str",
        "    params: dict[str, Any] = Field(default_factory=dict)",
        "",
        "",
        "class JsonRpcResponse(_ProtocolModel):",
        f'    jsonrpc: Literal["{proto["jsonrpc"]}"]',
        "    id: str | int | None",
        "    result: dict[str, Any] | None = None",
        "    error: JsonRpcError | None = None",
        "",
        "",
        "class NotificationEnvelope(_ProtocolModel):",
        '    """每个通知必带四字段（上位计划 §8.4-2）。"""',
        "",
        "    thread_id: str | None = None",
        "    turn_id: str | None = None",
        "    sequence: int | None = None",
        "    schema_version: str | None = None",
        "",
        "",
        "class JsonRpcNotification(NotificationEnvelope):",
        f'    jsonrpc: Literal["{proto["jsonrpc"]}"]',
        "    method: str",
        "    params: dict[str, Any] = Field(default_factory=dict)",
        "",
        "",
        "class InitializeParams(_ProtocolModel):",
        '    """initialize 必须是首个方法（上位计划 §8.1）。"""',
        "",
        "    client_info: dict[str, str] = Field(default_factory=dict)",
        "    protocol_versions: list[str] = Field(default_factory=list)",
        "    capabilities: dict[str, Any] = Field(default_factory=dict)",
        "    notification_preferences: list[str] = Field(default_factory=list)",
        "",
        "",
        "class InitializeResult(_ProtocolModel):",
        "    protocol_version: str",
        "    server_info: dict[str, str] = Field(default_factory=dict)",
        "    capabilities: dict[str, Any] = Field(default_factory=dict)",
        "    notification_preferences: list[str] = Field(default_factory=list)",
        "",
    ]
    return "\n".join(lines)


def render_typescript(schema: dict) -> str:
    proto = schema["protocol"]
    domain = schema["domain"]
    out: list[str] = [
        DO_NOT_EDIT_TS,
        "",
        f'export const PROTOCOL_NAME = "{proto["name"]}";',
        f"export const PROTOCOL_VERSION_MAJOR = {proto['version_major']};",
        f'export const PROTOCOL_VERSION_DRAFT = "{proto["version_draft"]}";',
        f'export const JSONRPC_VERSION = "{proto["jsonrpc"]}";',
        f"export const MAX_LINE_BYTES = {proto['wire']['max_line_bytes']};",
        "",
        "export interface MethodSpec {",
        "  kind: string;",
        "  write: boolean;",
        "  idempotency_key: boolean;",
        "}",
        "",
        "export const METHOD_REGISTRY: Record<string, MethodSpec> = {",
    ]
    for method in schema["methods"]:
        out.append(
            f'  "{method["name"]}": {{ kind: "{method["kind"]}", '
            f'write: {str(method["write"]).lower()}, '
            f'idempotency_key: {str(method["idempotency_key"]).lower()} }},'
        )
    out += [
        "};",
        "",
        "export const NOTIFICATION_TYPES = [",
    ]
    out += [f'  "{name}",' for name in schema["notifications"]]
    out += ["] as const;", "export type NotificationType = (typeof NOTIFICATION_TYPES)[number];", ""]
    out.append(
        "export const TURN_STATUSES = [%s] as const;"
        % ", ".join(f'"{s}"' for s in domain["turn_statuses"])
    )
    out.append("export type TurnStatus = (typeof TURN_STATUSES)[number];")
    out.append(
        "export const ITEM_KINDS = [%s] as const;"
        % ", ".join(f'"{k}"' for k in domain["item_kinds"])
    )
    out.append("export type ItemKind = (typeof ITEM_KINDS)[number];")
    out.append(
        "export const ITEM_LIFECYCLE = [%s] as const;"
        % ", ".join(f'"{s}"' for s in domain["item_lifecycle"])
    )
    out += [
        "",
        "/** 固定五字段错误信封（上位计划 §8.4-6）。 */",
        "export interface JsonRpcError {",
        "  code: number;",
        "  message: string;",
        "  retryable: boolean;",
        "  details: string;",
        "  trace_id: string;",
        "}",
        "",
        "export interface JsonRpcRequest {",
        '  jsonrpc: typeof JSONRPC_VERSION;',
        "  id: string | number;",
        "  method: string;",
        "  params?: Record<string, unknown>;",
        "}",
        "",
        "export interface JsonRpcResponse {",
        '  jsonrpc: typeof JSONRPC_VERSION;',
        "  id: string | number | null;",
        "  result?: Record<string, unknown>;",
        "  error?: JsonRpcError;",
        "}",
        "",
        "/** 每个通知必带四字段（上位计划 §8.4-2）。 */",
        "export interface NotificationEnvelope {",
        "  thread_id?: string;",
        "  turn_id?: string;",
        "  sequence?: number;",
        "  schema_version?: string;",
        "}",
        "",
        "export interface JsonRpcNotification extends NotificationEnvelope {",
        '  jsonrpc: typeof JSONRPC_VERSION;',
        "  method: NotificationType;",
        "  params?: Record<string, unknown>;",
        "}",
        "",
    ]
    return "\n".join(out)


def render_bundle(schema: dict) -> str:
    bundle = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": f'{schema["protocol"]["name"]} protocol bundle',
        "description": "GENERATED by scripts/protocol_codegen.py — DO NOT EDIT BY HAND.",
        "protocol": schema["protocol"],
        "definitions": {
            "error": {
                "type": "object",
                "required": schema["envelopes"]["error"],
                "properties": {
                    "code": {"type": "integer"},
                    "message": {"type": "string"},
                    "retryable": {"type": "boolean"},
                    "details": {"type": "string"},
                    "trace_id": {"type": "string"},
                },
                "additionalProperties": False,
            },
            "notification_envelope": {
                "type": "object",
                "required": schema["envelopes"]["notification_envelope_required"],
            },
        },
        "methods": {
            method["name"]: {
                "kind": method["kind"],
                "write": method["write"],
                "idempotency_key": method["idempotency_key"],
            }
            for method in schema["methods"]
        },
        "notifications": schema["notifications"],
        "domain": schema["domain"],
        "reserved": schema["reserved"],
    }
    return json.dumps(bundle, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def generate() -> dict[str, str]:
    schema = load_schema()
    return {
        str(PY_INIT_OUT): DO_NOT_EDIT_PY + "\n",
        str(PY_OUT): render_python(schema),
        str(TS_OUT): render_typescript(schema),
        str(BUNDLE_OUT): render_bundle(schema),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Agent protocol codegen")
    parser.add_argument("--check", action="store_true", help="只校验零 diff，不写入")
    args = parser.parse_args()

    artifacts = generate()
    drifted: list[str] = []
    for path_text, content in artifacts.items():
        path = Path(path_text)
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            drifted.append(path_text)

    if args.check:
        if drifted:
            print("protocol codegen drift detected（运行 scripts/protocol_codegen.py 重新生成）:")
            for item in drifted:
                print(f"  - {item}")
            return 1
        print("protocol codegen in sync: OK")
        return 0

    for path_text, content in artifacts.items():
        path = Path(path_text)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"generated: {path.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
